name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: ./vendor/bin/pest

  deploy:
    runs-on: ubuntu-latest
    needs: test # HANYA JALAN KALAU TEST SUKSES
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/e-facility
            # Paksa ambil kode terbaru, buang perubahan lokal yang bikin conflict
            git fetch --all
            git reset --hard origin/main

            # Rebuild & Restart dengan paksa
            docker build --network=host -t e-facility .
            docker rm -f e-facility-app || true
            docker run -d \
              -p 8080:80 \
              --name e-facility-app \
              --env-file .env \
              -v $(pwd)/storage:/var/www/storage \
              e-facility

            # Post-deployment
            # docker exec e-facility-app php artisan migrate --force
            docker exec e-facility-app php artisan config:cache
            docker exec e-facility-app php artisan route:cache
            docker exec e-facility-app php artisan view:cache
            docker exec e-facility-app php artisan storage:link

            # Fix Permissions dari dalam Container (Tanpa Sudo VPS)
            docker exec -u root e-facility-app chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
            docker exec -u root e-facility-app chmod -R 775 /var/www/storage /var/www/bootstrap/cache
